name: deploy to gh-pages
on:
  push:
    branches:
    - master

jobs:
  job1:
    runs-on: windows-latest
    steps:
        - name: 更新代码
          uses: actions/checkout@master
        - name: 安装node
          uses: actions/setup-node@master
          with:
            node-version: '10.x'
        - name: 发布gh-pages
          run: cd web && npm i && cd ..&&npm i&&npm run compile&&npm run newgh
       
  