name: deploy to gh-pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout
      - name: Setup node
        uses: actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - run: cd web && npm i && cd ..
