name: deploy to gh-pages
on:
  push:
    branches:
    - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
        - name: 更新代码
          uses: actions/checkout@master
        - name: node安装
          uses: actions/setup-node@master
          with:
            node-version: '10.x'
        - name: 前端依赖包安装
          run: cd web && npm i && cd ..
        - name: cordova依赖包安装
          run: npm i
        - name: cordova添加平台
          run: npm run platform
        - name: 前端代码打包&cordova prepare
          run: npm run compile
        - name: deploy to gh-pages
          uses: JamesIves/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: platforms/browser/www # The folder the action should deploy.