name: deploy to gh-pages
on:
  push:
    branches:
    - master

jobs:
  job1:
    runs-on: windows-latest
    steps:
        - name: 更新代码
          uses: actions/checkout@master
        - name: 安装node
          uses: actions/setup-node@master
          with:
            node-version: '10.x'
        - name: 前端安装包依赖
          run: cd web && npm i && cd ..
        - name: cordova安装包依赖
          run: npm i
        - name: cordova删除平台
          run: cordova platform rm android browser
        - name: cordova添加平台
          run: cordova platform add android browser
        - name: build前端代码&cordova prepare
          run: npm run compile
        - name: 发布gh-pages
          run: npm run newgh
  