name: deploy to gh-pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: 更新代码
        uses: actions/checkout@master
      - name: 安装node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: 前端安装包依赖
        run: cd web && npm i && cd ..
      - name: cordova安装包依赖
        run: npm i
    steps:
      - name: build前端代码&cordova prepare
        run: npm run compile
      - name: 发布gh-pages
        run: npm run newgh
